feat(sdk): Expose `prepare_encrypted_file` function
matrix-org/matrix-rust-sdk pull request #1577
Opened 2023-02-25 00:03 UTC by swedgwood

Exposed a function for uploading encrypted files and preparing an `EncryptedFile`, this would be useful for people who are creating custom events (like me!) and want to leverage the existing `EncryptedFile` definition.

I'm not sure if this is the most sensible place for this function, feel free to suggest somewhere else more suitable if so

2023-02-27 07:10 UTC, poljar requested changes
Thanks for this. I think the places is fine, at least I can't think of any better place.

The docs could handle a bit more verbosity and an example, otherwise looks fine.

2023-02-27 15:27 UTC, poljar approved these changes
Thanks, looks good.

2023-02-28 08:08 UTC, poljar commented
Oh, seems that `cargo fmt` isn't happy yet. Could you run `cargo xtask fixup style` and push the resulting changes?

2023-03-03 08:42 UTC, jplatte commented on crates/matrix-sdk/src/encryption/mod.rs
> +    /// and uploading a provided reader.
```suggestion
    /// Construct a [`EncryptedFile`][ruma::events::room::EncryptedFile] by
    /// encrypting and uploading a provided reader.
```

2023-03-03 09:27 UTC, merged

2023-03-06 15:45 UTC, jplatte commented
Yes, this will be part of the release but no, there is no ETA for it.