Stop restarting all rooms from growing mode on sliding sync restarts
matrix-org/matrix-rust-sdk pull request #2192
Opened 2023-06-30 13:24 UTC by stefanceriu

Following the discussion [here](https://matrix.to/#/!kCCQTCfnABLKGGvQjo:matrix.org/$ivcgoI94OoNiueJyRFb7a0NIFBIzDookUhhj4Sy8BCc?via=matrix.org&via=element.io&via=one.ems.host) we believe that resetting the all rooms list and having it start paginating again gets in the way of receiving new data.
Empirically, asking for one "big" request instead of multiple ones is faster on the `bigtestaccount` but mine wasn't necessarily a very scientific test.

2023-06-30 13:52 UTC, stefanceriu commented
Switched this to ready for review so it runs the tests

2023-06-30 14:16 UTC, bnjbvr requested changes
We'd need to understand a bit more what the problem is before getting a change like this, especially rushing it just before a release creates a situation where people have to fix it in emergency mode, if it gets back broken later.

We'd absolutely need answers to questions asked by Ivan in chat:

- why room subscription isn’t working as expected?
- why was it slow before and it no longer is?
- how does it perform when the app has been in the background for a while (at least an hour or so) and resumes? (For an account that's in many many rooms.)

2023-06-30 15:17 UTC, Hywan commented
Don’t do that :-). Let’s see that on Monday.

2023-07-03 08:07 UTC, Hywan commented
I'm going to close this PR because it removes an important feature :-).

2023-07-03 08:07 UTC, closed without merging