Allow subscribing to `RoomInfo` updates
matrix-org/matrix-rust-sdk pull request #2411
Opened 2023-08-15 09:39 UTC by jplatte

Note to self: Probably should add a changelog entry.

2023-08-16 13:54 UTC, Hywan approved these changes
It looks good. The idea is to get notified when `RoomInfo` has been updated, but we don't really know which part has been modified. I wonder if that would be desired to avoid unnecessary updates on the client-user-app side? And to clarify: yeah, knowing which part has been modified is difficult.

2023-08-16 14:49 UTC, stefanceriu commented
This works well client side but we do get a couple of extra updates whenever we enter a room. I wouldn't expect any updates when that happens 🤔

2023-08-21 07:55 UTC, Hywan requested changes

2023-08-21 07:55 UTC, Hywan commented on bindings/matrix-sdk-ffi/src/room_info.rs
>              },
Should be removed, see #2421.

2023-08-24 11:57 UTC, Hywan approved these changes
Looks good to me. One minor note.

2023-08-24 11:57 UTC, Hywan commented on bindings/matrix-sdk-ffi/src/room.rs
> +        let latest_event = match self.inner.latest_event() {
This code is duplicated from [`matrix_sdk_ui::room_list_service::Room::latest_event`](https://github.com/matrix-org/matrix-rust-sdk/blob/7aa6981e372dac0e3af78a629a34f90e66a24c07/crates/matrix-sdk-ui/src/room_list_service/room.rs#L147-L161). Don't you believe we can refactor to get this code in a single-place?

2023-08-24 11:58 UTC, Hywan commented
@jplatte Do you think it's just multiple updates, or a bug, in https://github.com/matrix-org/matrix-rust-sdk/pull/2411#issuecomment-1680761307?

2023-08-24 12:02 UTC, jplatte commented
Sounds like it *might* be a bug, but hard to tell. Doesn't sound like it's a problem outside of causing a bit of inefficiency though, so we could merge and investigate afterwards, right?

2023-08-24 12:03 UTC, jplatte commented
Waiting on feedback from the next test run before merging either way though.

2023-08-24 12:58 UTC, stefanceriu commented
> but I'm fine with that.

Yeah, I agree. It's fine. I'm going to try testing it soon, I promise 😁

2023-08-25 09:39 UTC, merged