feat(ui): Reset `Timeline` when a user is ignored/unignored
matrix-org/matrix-rust-sdk pull request #2467
Opened 2023-08-28 13:21 UTC by Hywan

Work in Progress

2023-08-31 12:49 UTC, Hywan commented
@jplatte Ready to review!

2023-08-31 14:40 UTC, jplatte requested changes

2023-08-31 14:40 UTC, jplatte commented on crates/matrix-sdk-ui/src/timeline/inner/mod.rs
> +        .switch()
I don't think this should be part of the "inner" bits of the timeline. Can you revert all the changes in this file and the unit tests please, and move the listening for the ignoreu user list changes one level higher, in the `timeline` module? (also, I think the `RwLock` thing should be a separate PR, if we want to do it at all – if we do the `eyeball-im` changes discussed today we probably don't need it)

2023-09-04 15:53 UTC, closed without merging

2023-09-04 15:53 UTC, jplatte commented
This has been implemented in a different way in #2504.