oidc: allow http scheme during discovery
matrix-org/matrix-rust-sdk pull request #2642
Opened 2023-09-28 16:02 UTC by kegsay

This is to enable entirely local stacks of Element X to work correctly. It's mostly seamless (no ffi changes) because of the slightly dubious check on the issuer for a `.` - if it does _not_ exist then we allow insecure lookups, on the basis that issuers like `mas` or `localhost` are not on public DNS.

2023-09-28 16:53 UTC, kegsay commented
Happy with whatever you decide, I just might need pointers on where to touch.

2023-09-29 10:22 UTC, bnjbvr requested changes
Almost perfect, thanks!

2023-09-29 10:22 UTC, bnjbvr commented on crates/matrix-sdk/src/authentication.rs
> +    pub(crate) insecure_discover_oidc: bool,
Could you put this in `OidcCtx` instead?

2023-09-29 11:15 UTC, bnjbvr commented on crates/matrix-sdk/src/authentication.rs
> +    pub(crate) insecure_discover_oidc: bool,
Done.

2023-09-29 11:16 UTC, bnjbvr approved these changes

2023-09-29 11:29 UTC, merged