Remove `E2EEenabled` flag from the rust sdk.
matrix-org/matrix-rust-sdk pull request #2847
Opened 2023-11-14 09:22 UTC by toger5

This is a deprecated flag for element call using livekit. It is replaced by the `password` and the `perParticipantE2EE` flag. If `perParticipantE2EE` is set to `false`
and there is now password encryption is disabled implicitly.

- [ ] Public API changes documented in changelogs (optional)

Signed-off-by:

2023-11-17 16:04 UTC, bnjbvr requested changes

2023-11-17 16:27 UTC, toger5 commented on crates/matrix-sdk/src/widget/settings/element_call.rs
> +            let expected_elements = ("perParticipantE2EE".to_owned(), "true".to_owned());
Sorry the comment was wrong. I was misinformed at the point of writing. (The core part: that this is deprecated) was correct. The reason why wasnt.

2023-11-17 16:29 UTC, toger5 commented on crates/matrix-sdk/src/widget/settings/element_call.rs
> +            let expected_elements = ("perParticipantE2EE".to_owned(), "true".to_owned());
But thanks for flaggin the test. Its not good as is. (I at least need to update the assert log.

2023-11-20 10:25 UTC, bnjbvr approved these changes
Thanks!

One small question: we're never translating from a raw URL with encoded query parameters to an `EncryptionSystem`, are we? If so, is there a test showing which we prefer between `PerParticipantKeys` and `SharedSecret` when both are set?

2023-11-20 10:25 UTC, bnjbvr commented on bindings/matrix-sdk-ffi/src/widget.rs
>      /// Equivalent to the element call url parameters:
(sorry about the nitpick, trying to be consistent with the previous comments :grin:)

```suggestion
    /// Equivalent to the element call url parameter:
```

2023-11-20 10:25 UTC, bnjbvr commented on bindings/matrix-sdk-ffi/src/widget.rs
>      /// Equivalent to the element call url parameters:
```suggestion
    /// Equivalent to the element call url parameter:
```

2023-11-20 15:41 UTC, toger5 commented
We only do it in the opposite direction: `EncryptionSystem` -> raw url and never the other way around.

The other way around is only done in element call (the webapp/widget). There we have a clear order of what we use. (its outside of the rust sdk logic. Even this is already not a perfect fit to have in the rust sdk but otherwise ios and android would need to do this by themselves and it is very encapsulated so the rust sdk is a good place to make it reliable/patchable and correct on both systems)

2023-11-20 15:43 UTC, merged