ffi: Support banning, unbanning and kicking users.
matrix-org/matrix-rust-sdk pull request #2915
Opened 2023-12-07 11:28 UTC by pixlwave

`can_ban` and `can_kick` already exist and from what I can tell unbanning is covered by the `ban` power level.

2023-12-07 13:24 UTC, Hywan requested changes
Adding a test for `unban_user` would be very appreciated. Apart from that, the PR looks good, thanks!

2023-12-07 13:24 UTC, Hywan commented on bindings/matrix-sdk-ffi/src/room.rs
> +    pub async fn ban_user(
The FFI API is designed for your needs mostly. If you believe it's fine as so, then I'm fine with it.

2023-12-07 13:24 UTC, Hywan commented on bindings/matrix-sdk-ffi/src/room.rs
> +        Ok(self.inner.ban_user(&user_id, reason.as_deref()).await?)
`as_deref` is nice here, well done! (I know you're learning Rust :-)).

2023-12-07 13:24 UTC, Hywan commented on crates/matrix-sdk/src/room/mod.rs
> +    }
You can update this test case to test `unban_user` https://github.com/matrix-org/matrix-rust-sdk/blob/main/crates/matrix-sdk/tests/integration/room/joined.rs#L109-L130.

2023-12-07 14:41 UTC, pixlwave commented on bindings/matrix-sdk-ffi/src/room.rs
> +    pub async fn ban_user(
Ok, then lets leave it like this for now. Can come back to this later if it makes sense in actual use.

2023-12-12 15:12 UTC, bnjbvr approved these changes

2023-12-12 15:13 UTC, merged