e2ee: commit the application transaction just after generating one-time keys
matrix-org/matrix-rust-sdk pull request #2930
Opened 2023-12-11 17:02 UTC by bnjbvr

See commit messages for details. I've gotten several EX devices wedged, and this is my biggest guess so far why it has happened in the first place.

2023-12-11 17:07 UTC, jplatte approved these changes
Apart from the fact that I've never heard the term "applicative transaction", looks good.

2023-12-11 17:09 UTC, bnjbvr commented
> Apart from the fact that I've never heard the term "applicative transaction", looks good.

You're right, this is made up vocabulary as of today, to disambiguate from sqlite- (or indexeddb, for that matter) level transactions.

2023-12-11 17:14 UTC, jplatte commented
Maybe "application-level"? "applicative" has an existing meaning [in functional programming](https://hackage.haskell.org/package/base-4.19.0.0/docs/Control-Applicative.html).

2023-12-12 13:29 UTC, bnjbvr commented
Ah yeah, I would argue people would think more immediately of applicative as "relating to an application" :-)

2023-12-12 16:17 UTC, uhoreg approved these changes
Flushing a transaction seems to be contrary to how transactions are normally supposed to work (all-or-nothing), but I guess it works here.

2023-12-13 08:20 UTC, BillCarsonFr requested changes

2023-12-13 08:20 UTC, BillCarsonFr commented on crates/matrix-sdk-crypto/src/machine.rs
> +            // `StoreTransaction` fails, but we've uploaded keys in the
How would it happen? If the store transaction fails, then the `receive_sync_changes` will fail, then the whole sync will fail and the keys wont be uploaded?

I think that in that case the sync token wouldn't be persisted, so the app will try again the same sync?

2023-12-14 09:14 UTC, Hywan approved these changes
Looks good to me, thanks!

2023-12-14 11:36 UTC, bnjbvr commented
Discussed on chat, it's probably not a fix to the issue I've observed, since the OTKs aren't uploaded at the same time a store transaction is alive. Instead, we'll add more logs to try to understand which keys are generated twice.

2023-12-14 11:36 UTC, closed without merging

2023-12-14 11:45 UTC, richvdh commented
This was an attempt to fix https://github.com/matrix-org/matrix-rust-sdk/issues/1415