Discard session API and bindings for `Room`
matrix-org/matrix-rust-sdk pull request #2941
Opened 2023-12-13 16:29 UTC by BillCarsonFr

- [ ] Public API changes documented in changelogs (optional)

Signed-off-by:

2023-12-13 16:42 UTC, Hywan requested changes
Thanks for the PR. Why is the name different in `matrix-sdk-ffi`?
Also, is it possible to get tests or do you feel that's not mandatory?

2023-12-13 16:42 UTC, Hywan commented on crates/matrix-sdk/CHANGELOG.md
> +- Add new method `force_discard_session` on `Room` that allows to discard the current
```suggestion
- Add new method `discard_room_keys` on `Room` that allows to discard the current
```

2023-12-14 09:12 UTC, Hywan commented
I prefer to keep the same name amongst the crates. We don't really want to mess with emote names 🙂.

2023-12-14 10:02 UTC, bnjbvr requested changes
Can you add a test in the SDK please?

2024-02-01 12:52 UTC, poljar commented
What's the state of this? Is this still needed?

2024-02-08 11:06 UTC, poljar commented
> I prefer to keep the same name amongst the crates. We don't really want to mess with emote names 🙂.

I agree, the names in the public API of the SDK should use the `room` terminology, the bindings should just re-expose what the SDK does and call it the same.

2024-02-20 12:36 UTC, poljar approved these changes
There were still some small issues, but I dragged this over the finish line.

2024-02-20 12:36 UTC, merged