Update logger.rs (Extend the logging callback interface in matrix-sdk-crypto-ffi #1759)
matrix-org/matrix-rust-sdk pull request #2943
Opened 2023-12-13 18:05 UTC by Rudraksh2003

#1759 
 in this issue, I change according to the description  [matrix-rust-sdk/bindings/matrix-sdk-crypto-ffi/src/logger.rs]
Lines 8 to 15 in [b033508](https://github.com/matrix-org/matrix-rust-sdk/commit/b033508e9bbf6eafa2eaac174ea412cc97a2c640)

Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
660 York Street, Suite 102,
San Francisco, CA 94110 USA

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

Signed-off-by: Rudraksh <rudrakshladdha@gmail.com>

2023-12-14 08:40 UTC, Hywan requested changes
Thank you for your contribution! It's really appreciated 🙂.

First off, `log` has been removed, and so the code is broken. You need to update `impl Write for LoggerWrapper`.

Second, this `impl Write for LoggerWrapper` will always redirect all writes to a single `log` method. To avoid that, it's desirable to impl `MakeWriter::make_writer_for` in the `impl MakeWriter for LoggerWrapper`.

I was also about to suggest to avoid closing `LoggerWrapper` inside `make_writer` by having this code:

```rust
impl<'a> Write for &'a LoggerWrapper {
    // same code
}

impl<'a> MakeWriter<'a> for LoggerWrapper {
    type Writer = &'a Self;

    fn make_writer(&'a self) -> Self::Writer {
        self
    }
}
```

but it's going to be quite complex to implement `make_writer_for` with a reference to `LoggerWrapper`. I think it's good to keep returning an owned value of `LoggerWrapper`, but it should contain a level I believe. Something like this:

```rust
pub struct LoggerWrapper {
    inner: Arc<Mutex<Box<dyn Logger>>>,
    level: tracing_core::Level,
}

impl MakeWriter<'_> for LoggerWrapper {
    type Writer = Self;

    fn make_writer(&self) -> Self::Writer {
        Self { inner: self.inner.clone(), level: tracing_core:Level::DEBUG }
    }

    fn make_writer_for(&self, meta: &tracing_core::Metadata<'_>) -> Self::Writer {
        Self { inner: self.inner.clone(), level: meta.level().clone() }
    }
}
```

Finally, inside `impl Write for LoggerWrapper`, you can decide which methods on the logger to call based on the level.

Thoughts?

2023-12-14 12:24 UTC, Rudraksh2003 commented
Sir, now I have solved the issue according to your suggestion.
 Thank you, sir, for giving me a descriptive suggestion to handle this code, which helped me a lot to understand.

2023-12-14 13:25 UTC, Hywan requested changes

2023-12-14 13:25 UTC, Hywan commented on bindings/matrix-sdk-crypto-ffi/src/logger.rs
> +            tracing_core::Level::ERROR => self.inner.lock().unwrap().log_error(message, String::new()),
You may want to write `use tracing_core::Level` at the top of the file, so that it makes the code shorter.

2023-12-14 13:25 UTC, Hywan commented on bindings/matrix-sdk-crypto-ffi/src/logger.rs
> +                             level: tracing_core::Level::DEBUG,  };
Please fix formatting.

2023-12-15 11:46 UTC, Hywan commented
Can you please fix the CI errors?

2024-02-02 10:14 UTC, closed without merging

2024-02-02 10:14 UTC, poljar commented
This PR didn't see any activity for quite a while, it also has some very basic error like missing imports. 

Please check your work locally with `cargo check`, or if you're working on the bindings with `cargo check -p matrix-sdk-crypto-ffi`. Also check out `cargo xtask help` which can replicate what we do on the CI locally, more info can be found here: https://github.com/matrix-org/matrix-rust-sdk/blob/main/CONTRIBUTING.md#testing.

Closing now, feel free to reopen or open a new PR if you'd like to move this forward.