Improving documentation: Can push encrypted events to device
matrix-org/matrix-rust-sdk pull request #3003
Opened 2024-01-10 16:26 UTC by Velin92

Given the following comment:https://github.com/matrix-org/matrix-rust-sdk/pull/2840#issuecomment-1875587994 
The name and the documentation of the API might have been a bit misleading since we are not actively checking the supported state of the homeserver, but just the current state of the account data to verify if encrypted events are pushed to the client or not.

2024-01-10 18:33 UTC, giomfo approved these changes
LGTM 👍

2024-01-11 09:16 UTC, bnjbvr approved these changes

2024-01-11 09:18 UTC, bnjbvr requested changes
Can you use meaningful commit messages, as they help writing our TWiM / matrix sync reports, please?

(and since you'll be updating the commits, can you squash them into a single commit please too)

Thanks!

2024-01-11 10:37 UTC, bnjbvr approved these changes
Grazie mille!

2024-01-11 13:13 UTC, merged