sliding_sync : fix room account data not being processed when there is no other changes in the room
matrix-org/matrix-rust-sdk pull request #3032
Opened 2024-01-18 17:57 UTC by ganfra

There was an issue with the sliding sync processing where room account data are not processed when the associated room has no other changes.

Don't hesitate to change how it's done, but at least you know where to look at!

2024-01-18 20:15 UTC, ganfra commented on crates/matrix-sdk-base/src/sliding_sync.rs
> +                        self.handle_room_account_data(room_id, events, &mut changes).await;
I'm not sure if we should add those rooms to the joined/left rooms of the `SyncResponse`
I don't know how to get the Membership here so we know if it's a `JoinedRoom` or `LeftRoom` instance.

2024-01-19 06:53 UTC, stefanceriu commented on crates/matrix-sdk-base/src/sliding_sync.rs
> +                        self.handle_room_account_data(room_id, events, &mut changes).await;
It would be great if we could get our hands on the RoomInfo here so we can update it based on room account data changes.

2024-01-19 08:09 UTC, stefanceriu commented on crates/matrix-sdk-base/src/sliding_sync.rs
> +                        self.handle_room_account_data(room_id, events, &mut changes).await;
Perhaps something along these lines instead?

<img width="737" alt="Screenshot 2024-01-19 at 10 08 58" src="https://github.com/matrix-org/matrix-rust-sdk/assets/637564/af5eb9fe-9d47-42bf-a9ba-b53ab82deb88">

2024-01-19 10:32 UTC, bnjbvr requested changes
I think a better fix would be to take the `account_data.rooms` field, pass it mutably to `handle_sliding_sync_room` so whenever a room is handled, we *remove* it from `account_data.rooms`, and then after handling all the rooms subsection, we handle remaining rooms in `account_data.rooms`: those would be the only rooms that weren't present in the rooms subpart of the response.

Also we'd need to both add them to the changes struct (so they're saved in the database), as well as in the `new_rooms` (so they're handled by handlers of the sync response).

Can you include a regression test that shows what was fixed? It would be a test that doesn't pass on main, and that passes with your PR. You can look at `test_process_read_receipts` which fixed a similar bug.

2024-01-22 09:45 UTC, Hywan approved these changes
Thanks for the patch.
I think it is correct. I'm approving it, but I believe @bnjbvr should proof-read it again too.

2024-01-22 10:01 UTC, bnjbvr approved these changes
thanks, lgtm with Ivan's comments addressed.

2024-01-22 13:04 UTC, Hywan requested changes
I'm changing the review status, just so we know we wait on a couple of minor updates before merging.

2024-01-24 11:03 UTC, ganfra commented
@Hywan can we merge?

2024-01-25 08:11 UTC, bnjbvr reviewed
One final comment before hitting merge!

2024-01-25 08:11 UTC, bnjbvr commented on crates/matrix-sdk-base/src/sliding_sync.rs
>              Some(events.to_vec())
Taking the reference early forces you to reclone the same vector with the same content later. Could we do something like this instead:

```suggestion
        let room_account_data = if let Some(events) = rooms_account_data.remove(room_id) {
            self.handle_room_account_data(room_id, &events, changes).await;
            Some(events)
```

2024-01-25 09:26 UTC, bnjbvr approved these changes
![](https://media.giphy.com/media/Hw8vYF4DNRCKY/giphy.gif)

2024-01-26 12:34 UTC, merged