feat: Expose a room list filter for Invites only
matrix-org/matrix-rust-sdk pull request #3205
Opened 2024-03-11 12:54 UTC by stefanceriu

This PR adds a new room list filter that can be used to render invites only. Meant to work together with https://github.com/matrix-org/matrix-rust-sdk/pull/3203

2024-03-11 13:18 UTC, stefanceriu commented on crates/matrix-sdk-ui/src/room_list_service/filters/invite.rs
> +                }
heh, of course 🤦

2024-03-11 13:19 UTC, stefanceriu commented
> Can we have test please :-)?

hah, of course, just wanted to make sure I'm going the right path before I write any

2024-03-13 09:42 UTC, Hywan requested changes
The tests looks good, thanks! One minor refactoring is necessary for the sake of consistency with the `non_left` filter, but it's just a minor details :-}.

2024-03-13 09:42 UTC, Hywan commented on crates/matrix-sdk-ui/src/room_list_service/filters/invite.rs
> +}
To be consistent with the `non_left` filter, I think we should revisit the code a little bit:

```suggestion
struct InviteRoomMatcher<F>
where
    F: Fn(&RoomListEntry) -> Option<RoomState>,
{
    state: F,
}

impl<F> InviteRoomMatcher<F>
where
    F: Fn(&RoomListEntry) -> Option<RoomState>,
{
    fn matches(&self, room: &RoomListEntry) -> bool {
        if !matches!(room, RoomListEntry::Filled(_) | RoomListEntry::Invalidated(_)) {
            return false;
        }

        if let Some(state) = (self.state)(room) {
            state == RoomState::Invited
        } else {
            false
        }
    }
}

/// Create a new filter that will accept all filled or invalidated entries, but
/// filters out rooms that are not invites (see
/// [`matrix_sdk_base::RoomState::Invited`]).
pub fn new_filter(client: &Client) -> impl Filter {
    let client = client.clone();

    let matcher = InviteRoomMatcher {
        state: move |room| {
            let room_id = room.as_room_id()?;
            let room = client.get_room(room_id)?;
            Some(room.state())
        },
    };

    move |room_list_entry| -> bool { matcher.matches(room_list_entry) }
}
```

I think consistency is preferable here, even if your code is correct!

2024-03-13 10:35 UTC, Hywan approved these changes
Looks good to me, thanks!

2024-03-13 10:43 UTC, merged