event cache: internalize handling of the account data
matrix-org/matrix-rust-sdk pull request #3276
Opened 2024-03-26 16:03 UTC by bnjbvr

This is a relatively simple change: this moves handling the fully read marker for a given room into the event cache, so listeners can react to a specific event for that, instead of handling themselves all the account data changes.

Not sure if that's a better API than just returning all the account data changes, so I would love feedback on this. At least it's sufficient for the UI timeline use case, and so it seems sufficient right now (and we could make it different later).

Part of #3058.

2024-03-27 11:37 UTC, andybalaam approved these changes
Looks good, and I prefer a more-specific API in general terms. I don't think I understand well enough to comment on this exact choice of API.

2024-03-27 11:37 UTC, andybalaam commented on crates/matrix-sdk/src/event_cache/mod.rs
> +                    // Propagate to observers. We ignore the fact there aren't any.
```suggestion
                    // Propagate to observers. (We ignore the error if there aren't any.)
```

2024-03-27 11:37 UTC, andybalaam commented on crates/matrix-sdk/src/event_cache/mod.rs
> +            // Propagate to observers. We ignore the fact there aren't any.
```suggestion
            // Propagate to observers. (We ignore the error if there aren't any.)
```

2024-03-28 09:57 UTC, Hywan requested changes
Thanks for the work. However, I'm not sure about this changes. The idea is to remove `RoomEventCacheUpdate` to replace it by a single `Stream<Item = Vec<VectorDiff<SyncTimelineEvent>>>`, and I don't know how this feature could fit in the next API.

2024-03-28 11:31 UTC, bnjbvr commented
The timeline will always need to listen to those account data changes, or at least the "read marker has been updated" event, so:

- either we say the event cache only strictly streams event updates, and does not pass forward the "read marker has been updated" event — which means that the timeline now needs to listen to 1. the event cache updates for a room, 2. also the JoinedRoomUpdates for a room, which seems messy
- or the event cache has two kinds of updates: strict event updates (via Vec<VectorDiff<SyncTimelineEvent>>), or other kind of updates (like the one introduced in this PR)
- or instead of streaming `SyncTimelineEvent`, we stream a thin wrapper that also contains a bool indicating whether this event is the target of the read marker. It sounds a bit wasteful to me, since it'll be false for most updates, and it's not clear that this will cleanly extend to other info streamed from the event cache, e.g. about read receipts

2024-03-28 12:39 UTC, Hywan approved these changes
After a discussion about the possible evolution of this API in private, I'm approving this PR :-). Thanks!

2024-03-28 16:59 UTC, merged