Expose ed25519/curve25519 keys in bindings
matrix-org/matrix-rust-sdk pull request #3420
Opened 2024-05-16 08:29 UTC by BillCarsonFr

The Element-X rageshakes are lacking device keys info, see https://github.com/element-hq/element-x-ios/issues/2550

This change exposes these so that it can be used by the app.
The `ed25519_key()` was already present in the sdk but not exposed in bindings. I added a second one for `curve25519_key()` in both sdk and bindings.

Can be accessed via `client.encryption().curve25519Key()` in the aps

- [ ] Public API changes documented in changelogs (optional)

Signed-off-by:

2024-05-16 08:37 UTC, bnjbvr requested changes
Please follow the contribution guidelines when it comes to PR names.

2024-05-17 09:28 UTC, poljar commented
Could you make CI happy? I think that this is should be a pretty trivial change, but CI failures need to be addressed.

2024-05-17 10:08 UTC, BillCarsonFr commented
> Could you make CI happy? I think that this is should be a pretty trivial change, but CI failures need to be addressed.

Oh sry, I missed the failing checks

2024-05-17 11:55 UTC, poljar approved these changes

2024-05-17 11:55 UTC, merged