Add `StateEventType::RoomEncryption` to capabilities.
matrix-org/matrix-rust-sdk pull request #3506
Opened 2024-06-04 12:35 UTC by toger5

also add TODO comment to remove. `org.matrix.msc3401.call` once possible.

- [ ] Public API changes documented in changelogs (optional)

Signed-off-by:

2024-06-04 12:36 UTC, stefanceriu approved these changes
lgtm 👍

2024-06-04 14:23 UTC, bnjbvr approved these changes

2024-06-04 14:24 UTC, bnjbvr requested changes
Can you also run `cargo xtask fixup style`?

2024-06-04 14:24 UTC, bnjbvr commented on bindings/matrix-sdk-ffi/src/widget.rs
> +                event_type: StateEventType::RoomEncryption.to_owned(),
```suggestion
                event_type: StateEventType::RoomEncryption.to_string(),
```

2024-06-06 17:31 UTC, bnjbvr approved these changes

2024-06-06 17:31 UTC, merged