crypto: Move device_keys to DecryptedOlmV1Event as per MSC4147
matrix-org/matrix-rust-sdk pull request #3633
Opened 2024-07-01 14:52 UTC by andybalaam

Part of https://github.com/matrix-org/matrix-rust-sdk/issues/3542

Fixes a mistake I made in https://github.com/matrix-org/matrix-rust-sdk/pull/3556 - I included `device_keys` in the `content` and it should be outside as per [MSC4153](https://github.com/matrix-org/matrix-spec-proposals/pull/4153)

2024-07-02 06:05 UTC, poljar requested changes
Looks good, but now that https://github.com/matrix-org/matrix-rust-sdk/pull/3517 has been merged we can add a test confirming that we put things in the right place.

2024-07-03 07:49 UTC, poljar commented
> > Looks good, but now that #3517 has been merged we can add a test confirming that we put things in the right place.
> 
> Can I have a hint on how to write a test? I've spent the day trying to call `matrix_sdk_crypto::olm::session::Session::encrypt` or `matrix_sdk_crypto::identities::device::ReadOnlyDevice::maybe_encrypt_room_key` or similar and then feed the result into `matrix_sdk_crypto::olm::account::Account::decrypt_to_device_event`to check that the device keys come through, but I haven't managed to find the right incantation and I can't find any tests that directly call these things.
> 
> Is there an example I can follow? Thanks

#3517 added a test which uses the weaker `serde_json::Value` type to check this: https://github.com/matrix-org/matrix-rust-sdk/blob/2507a450df4bfe12d163a8141a2e47932c1ee21c/crates/matrix-sdk-crypto/src/olm/session.rs#L351-L353

You could modify this test to also check using our stronger type you modified.

2024-07-03 11:14 UTC, andybalaam commented
> You could modify this test to also check using our stronger type you modified.

Thank you, done in 46b4d00b6e

2024-07-03 11:16 UTC, andybalaam commented
Out of interest, do you know why [`Session::encrypt`](https://github.com/uhoreg/matrix-rust-sdk/blob/fc1dabf312a28457bfd2d189bc4c9bc04c4ebac8/crates/matrix-sdk-crypto/src/olm/session.rs#L153) uses `json!` instead of constructing and serializing a `DecryptedOlmV1Event`?

2024-07-03 11:44 UTC, poljar commented
> Out of interest, do you know why [`Session::encrypt`](https://github.com/uhoreg/matrix-rust-sdk/blob/fc1dabf312a28457bfd2d189bc4c9bc04c4ebac8/crates/matrix-sdk-crypto/src/olm/session.rs#L153) uses `json!` instead of constructing and serializing a `DecryptedOlmV1Event`?

Nowadays probably just for historic reasons, we didn't use to have the `DecryptedOlmV1Event` type. But I'm not completely sure that we can just exchange the types, the `C` in `DecryptedOlmV1Event` has more trait bounds, if it's possible it certainly isn't easy.

2024-07-03 11:48 UTC, poljar approved these changes

2024-07-03 13:29 UTC, andybalaam commented on crates/matrix-sdk-crypto/src/olm/session.rs
> +        let plaintext: DecryptedOlmV1Event<DummyEventContent> =
Happy to do so, but can you explain why it's useful?

2024-07-03 13:34 UTC, poljar commented on crates/matrix-sdk-crypto/src/olm/session.rs
> +        let plaintext: DecryptedOlmV1Event<DummyEventContent> =
Well it double checks that we're serializing to the static string `org.matrix....`, while using the `DecryptedOlmV1Event` type, we're checking that the serialization and deserialization is using the same format, but not exactly which format.

2024-07-04 10:05 UTC, andybalaam commented on crates/matrix-sdk-crypto/src/olm/session.rs
> +        let plaintext: DecryptedOlmV1Event<DummyEventContent> =
Good point, I like it. Done in 1c5f302681

2024-07-04 10:22 UTC, merged