Expose login with email + password on the client
matrix-org/matrix-rust-sdk pull request #3883
Opened 2024-08-22 17:55 UTC by zzorba

Login via OIDC and username were exposed in the ffi, but login via email was seemingly not.  This adds a `login_with_email` method to the `Client` object.

- [ ] Public API changes documented in changelogs (optional)

Signed-off-by:

2024-08-23 07:45 UTC, Hywan requested changes
Thanks for the contribution!

I'm fine with it. Can you please merge your 2 commits into a single one, and address the formatting comment, so that I can merge your PR? Thanks!

2024-08-23 07:45 UTC, Hywan commented on bindings/matrix-sdk-ffi/src/client.rs
> +        Ok(())
I know we are all stressed, but the code needs to breath 😉.

```suggestion
        let mut builder = self
            .inner
            .matrix_auth()
            .login_identifier(UserIdentifier::Email { address: email }, &password);

        if let Some(initial_device_name) = initial_device_name.as_ref() {
            builder = builder.initial_device_display_name(initial_device_name);
        }

        if let Some(device_id) = device_id.as_ref() {
            builder = builder.device_id(device_id);
        }

        builder.send().await?;

        Ok(())
```

2024-08-23 15:41 UTC, zzorba commented
Thank you for accepting this PR, I've made your suggested changes and flattened the commits.

2024-08-26 16:23 UTC, Hywan approved these changes

2024-08-26 16:23 UTC, merged