sdk: Add support for authenticated media stable feature
matrix-org/matrix-rust-sdk pull request #3961
Opened 2024-09-08 09:22 UTC by zecakeh

Was added post-merge to the MSC in https://github.com/matrix-org/matrix-spec-proposals/pull/4180 for servers that support authenticated media but do not support all of Matrix 1.11 yet.

Requires a kind of hack to force Ruma to select the stable endpoint by ignoring the real versions advertised by the homeserver for this particular endpoint.

2024-09-09 06:33 UTC, Hywan approved these changes
It looks good to me, thanks!

2024-09-09 06:36 UTC, Hywan requested changes
Is it possible to assert in the tests that we are actually forcing the matrix version?

2024-10-08 07:01 UTC, zecakeh commented
@Hywan, maybe you can clarify what you meant, if it is blocking the review?

2024-10-08 10:21 UTC, Hywan commented
Hmm, it seems fine actually, I don't remember exactly what I was referring to. I'm approving and merging this PR.

2024-10-08 10:21 UTC, Hywan approved these changes

2024-10-08 10:21 UTC, merged