feat: Implement `EventCacheStoreLock::lock()` with poison error, and `::lock_unchecked`
matrix-org/matrix-rust-sdk pull request #4285
Opened 2024-11-18 16:05 UTC by Hywan

Since https://github.com/matrix-org/matrix-rust-sdk/pull/4192, the event cache has a cross-process lock via `EventCacheLock`. It brings a `lock` method. Great! However, the caller is not aware if the lock has been acquired from the same holder or from another holder. The _holder_ refers to the process name usually. If the _holder_ of the lock changes, it means the in-memory data might now be invalid! That's absolutely terrifying. Imagine the following scenario:

- the main app process adds events inside the event cache store
- the main app process is paused
- the push notification process is fired, and adds events inside the event cache store
- the main app process is resumed
- now what? how this process is able to know its data are invalid and should be reloaded?

Poor main app process. We must help this poor main app process, don't we?

Hence this PR.

It introduces a _generation_ counter. The principle is really simple: every time the lock is acquired from _another holder_, the _generation_ is incremented by one. The generation does **not** change if the holder stays the same between lock acquisitions.

So.

* The first patch do that: a `generation` value is added inside the stores (e.g. `matrix-sdk-sqlite`).
* Next, `EventCacheStoreLock::lock` is renamed `lock_unchecked`. Why do we want an _unchecked_ version of the lock? What does it even mean? A lock can be poisoned, but sometimes we just don't care! If we want to add a media in the cache, there is no in-memory invalidation involved. Using `lock_unchecked` is perfect in this case.
* After that, we do a bit of Rust magic with `BackingStore` being automatically implemented for all `Arc<T>` where `T: BackingStore`.
* And now we are ready to implement `LockableEventCacheStore::is_poisoned`. This “poisoning” API is restricted to the event cache; I didn't want to touch the `CrossProcessStoreLock` API. Maybe that would be useful for all cross-process store locks later, but for now, only event cache, nah!
* All pieces are ready. We can implement `EventCacheStoreLock::lock()`.
* Finally, the test parts.

It's better to review this PR commit-by-commit for your own sanity.

2024-11-19 14:02 UTC, bnjbvr requested changes
Thanks for making small commits, this made it easier to review.

## main comment

I have my doubts about exposing the fact the store has been poisoned to callers of the event cache store. **All the data that needs to be reset upon poisoning should be owned by the store itself**, so that it can reset internally, and obtaining the lock is transparent to the callers; otherwise, each call site now needs to reflect what they need to do in that case, and that doesn't make for a very ergonomic API at all (and the `Result<Result<>>` reflects that weirdness).

Does it make sense to you too?

## future directions

As discussed in the small chat we had today :) Those things can be implemented later, as follow-ups (even though I'd *love* to see the first item sooner rather than later :)).

### crypto store

Since this is implementing from scratch the same mechanics that existed for the crypto-store, I strongly think we should merge implementations, instead of having two implementations that are close to each other but different. I think we should do it sooner rather than later, otherwise we'd be shipping new tech debt :worried: 

### lock vs lock_unchecked

I like the idea of separating `lock()` from `lock_unchecked()`; I think we can go the next mile by splitting the store state into two parts:

- bits that are OK to touch while holding a lock, independently of other processes: the media cache is a good example of that, likely. This would go into its own data structure, conceptually a `SharedEventCacheStore`, and it would contain references or own those bits.
- bits that are not OK to touch while another process holds the lock, and that would need to be reset upon poisoning (aka no aliasing allowed), conceptually a `UniqueEventCacheStore`. This would contain the room events and such.

Then, to make it so that it's not possible to take the lock with `lock_unchecked` and touch the bits one is not allowed to, we'd slightly change the signatures of those two functions:

- `lock() -> Result<UniqueEventCacheStore, ...>`
- `lock_unchecked() -> Result<SharedEventCacheStore, ...>`

This way, we have static safety around those types, and it's not even possible to shoot oneself in the feet by misusing the lock.

2024-11-19 14:07 UTC, Hywan commented on crates/matrix-sdk-base/src/event_cache/store/mod.rs
> +            Err(EventCacheStoreLockPoisonError(event_cache_store_lock_guard))
The `EventCacheStoreLock` isn't responsible to invalidate/refresh the in-memory data we have. However, `EventCache` and other users of this lock _are_ responsible of that. Example: every time `EventCache` is calling `store.lcok()`, and is responsible of refreshing its own data. I don't see how `EventCacheStoreLock` can track all data used everywhere related to the event cache store. It's basically impossible.

Remember that the `EventCache` uses the `EventCacheStoreLock` to read load data from the store into memory, or to save data from memory into the store. The `EventCacheStoreLock` has no idea where the data that it has loaded or saved are used, and by whom.

2024-11-19 15:32 UTC, andybalaam commented
I will hold off on reviewing until you let me know the ideas have settled a bit or you want my input.

I also would like to share logic where it makes sense with the crypto store.

2024-11-20 08:32 UTC, Hywan commented
I totally agree we should share the logic with the crypto store. However it implies a non-trivial work to move this generation and lock poison mechanism into the `CrossProcessStoreLock` API. I prefer to go step-by-step, especially because I'm running out of time to finish the event cache persistent storage. This PR is for the event cache. I agree a refactoring with all cross-process store locks will be necessary once this patch will land and once the design has proven to be mature. Moreover, the work on the crypto store isn't finished and I'm not confident I can rewrite _and_ complete it. I think we should have a team discussion about that: to come with a solid design together. Having a bit of “duplication” isn't dramatically bad here: it's a _specific solution_, and I agree having a _generic solution_ would be an improvement, but I don't see that as a blocker.

2024-11-20 10:34 UTC, bnjbvr commented on crates/matrix-sdk-base/src/event_cache/store/mod.rs
> +            Err(EventCacheStoreLockPoisonError(event_cache_store_lock_guard))
>  I don't see how EventCacheStoreLock can track all data used everywhere related to the event cache store. It's basically impossible.

If it owns it, as I suggested, it doesn't need to track it.

A thought experiment: if we keep the current API (modulo making the return type of the lock look better, to not have to deal with a result of a result), then the next thing I would implement is a thin wrapper on top of the lock, to invalidate the data manually. So it seems like this is just kicking the can down the road, and pushing the problem elsewhere in our architecture.

Moreover, using a generic parameter for the data stored along the lock and that needs a reset would nicely solve the layer separation. A thin `trait InvalidatableData { fn invalidate(); }` (lol @ naming)  would be sufficient to represent data that needs invalidation, and mocking it in testing situations should be straightforward (use a bool, toggle it when `invalidate()` is called).

I am really not sure the splitting of responsibility gives us anything valuable, so I still need to be convinced this is the best approach.

Would you have WIP code making use of this, so I can get a better opinion about how it's going to be used?

2024-11-20 13:57 UTC, Hywan commented
After a team discussion, here is the new plan:

- create new crate: `matrix-sdk-cross-process-lock`
- move and rename `CrossProcessStoreLock` to `CrossProcessLock` inside `matrix-sdk-cross-process-lock`
- improve the `CrossProcessLock` to include the generation mechanism introduced in [#4285](https://github.com/matrix-org/matrix-rust-sdk/pull/4285/)
- add the `lock_unchecked` and `lock`+`PoisonError` logic inside this crate too, including the lock guards etc.
- create a trait to represent a “poisonable” lock

Once we have that, the following items can be triggered:

- `matrix-sdk-crypto` uses this new trait (+ friendly default to use `CrossProcessStoreLock` maybe?)
- either:
    - update the state store to be cross-process aware, then event cache store and crypto store use the state store
    - use a new front type, like `Stores`, that is cross-process aware, and that gives access to all the stores
- the event cache can implements `EventCacheData` that contains all in-memory data + owned access to the store (and reload in-memory data in case of poison)
- the crypto can implements `CryptoData` that contains all in-memory data + owned access to the store (and reload in-memory data in case of poison) \<- is it doable?
- same dance for the state store?

2025-01-17 14:52 UTC, poljar commented
What's the state of this PR, it sounds like it's abandoned?

2025-01-20 12:10 UTC, Hywan commented
It is not. We need to do this, https://github.com/matrix-org/matrix-rust-sdk/pull/4285#issuecomment-2488655073. If we close this PR, we might lose this project. Maybe we can open an issue to not forget the plan, and link the issue to this (closed) PR?

2025-08-14 05:17 UTC, bnjbvr commented
I don't think it makes sense to keep large PRs that have bitrot like this for a long time, especially when we know there's much more work to do. Thanks for the initial investigation, and please reopen if/when this is ready to review :)

2025-08-14 05:17 UTC, closed without merging