feat(sdk): Add method to get homeserver capabilities
matrix-org/matrix-rust-sdk pull request #495
Opened 2022-02-15 11:33 UTC by zecakeh

Useful to know if we can change the user password, among other things.

2022-02-15 12:38 UTC, zecakeh commented
Done

2022-02-15 13:50 UTC, poljar requested changes
Please no new unwraps in doc examples. Otherwise looks good.

2022-02-15 13:50 UTC, poljar commented on crates/matrix-sdk/src/client.rs
> +    /// # let homeserver = Url::parse("http://example.com").unwrap();
No need to unwrap.

2022-02-15 16:45 UTC, zecakeh commented
Unwrap removed

2022-02-16 17:26 UTC, gnunicorn approved these changes

2022-02-16 17:27 UTC, merged