feat: add .get_alias() method to the client
matrix-org/matrix-rust-sdk pull request #706
Opened 2022-05-23 14:31 UTC by lilydjwg

Let me try to fix my own issue https://github.com/matrix-org/matrix-rust-sdk/issues/673.

The method is named after ruma. I don't know if it should be kept the same but if not, I can give it a better name.

2022-05-23 14:34 UTC, jplatte commented on crates/matrix-sdk/src/client/mod.rs
> +#[cfgnot(target_arch = "wasm32")]
```suggestion
#[cfg(not(target_arch = "wasm32"))]
```

2022-05-23 14:36 UTC, jplatte approved these changes
I don't really care whether it's called `get_alias` or `resolve_alias`, but the code looks good to me 👍🏼

2022-05-23 14:40 UTC, poljar requested changes
Looks good, but we need to make CI happy. You can run `cargo xtask fixup` for that.

2022-05-23 14:41 UTC, lilydjwg commented
I'm sorry I made some stupid mistakes...I fixed it just now. I tried to run the tests locally but it used too much memory so I have to Ctrl-C.

2022-05-23 14:50 UTC, jplatte commented
There's still some formatting inconsistencies, can you please run `cargo +nightly fmt` locally?

2022-05-23 14:51 UTC, jplatte commented
Also, we're aware that testing the SDK takes way too much memory. We unfortuantely don't know exactly what's the problem, but maybe we should re-prioritize looking into that..

2022-05-23 14:58 UTC, lilydjwg commented
cargo fmt has been run.

I'm still running cargo xtask fixup. It needs to install and compile quite a lot things.

2022-05-23 17:06 UTC, jplatte commented
It looks like the test you added is failing.

2022-05-24 04:40 UTC, lilydjwg commented
The URL was wrong. It should have been fixed (I've run it on a server).

Also I decided to give it a better name.

2022-05-24 05:41 UTC, jplatte commented on crates/matrix-sdk/src/client/mod.rs
> +    /// Resolve a room alias to a room id and a list of servers which knows
```suggestion
    /// Resolve a room alias to a room id and a list of servers which know
```

2022-05-24 06:43 UTC, merged