feat: Rename `OlmMachine.share_group_session` to `OlmMachine.share_room_key`
matrix-org/matrix-rust-sdk pull request #723
Opened 2022-05-31 09:54 UTC by Hywan

As discussed with @poljar, the Matrix event we are creating is
`m.room.key`, so it's preferable to rename the function
`share_room_key`. Note: Olm calls the things an inbound group session,
that's where the name comes from, but it's not aligned with the
specification.

Thoughts?

2022-05-31 10:03 UTC, poljar requested changes
Looks good, but let's stick to `room key` since just `key` is quite unclear, there are many keys in matrix land. Also there seem to be a bit more places where we call the room keys a `group session`.

2022-05-31 10:03 UTC, poljar commented on crates/matrix-sdk-crypto-js/src/machine.rs
> +    /// Get to-device requests to share a key with users in a room.
```suggestion
    /// Get to-device requests to share a room key with users in a room.
```

2022-05-31 10:03 UTC, poljar commented on crates/matrix-sdk-crypto-js/src/machine.rs
>      /// Beware that a group session needs to be shared before this
```suggestion
    /// Beware that a room key needs to be shared before this
```

2022-05-31 10:03 UTC, poljar commented on crates/matrix-sdk-base/src/client.rs
> +    /// Get a to-device request that will share a key with users in a room.
```suggestion
    /// Get a to-device request that will share a room key with users in a room.
```

2022-05-31 15:30 UTC, Hywan commented on crates/matrix-sdk-crypto-js/src/machine.rs
>      /// Beware that a group session needs to be shared before this
:+1:

2022-05-31 15:31 UTC, Hywan commented on crates/matrix-sdk-crypto/src/machine.rs
>      /// Panics if a group session for the given room wasn't shared beforehand.
:+1:

2022-05-31 15:31 UTC, Hywan commented on crates/matrix-sdk-crypto/src/machine.rs
> +    /// Get to-device requests to share a key with users in a room.
:+1:

2022-05-31 15:32 UTC, Hywan commented on crates/matrix-sdk/src/room/joined.rs
> +    /// Share a key with users within the given room.
:+1:

2022-05-31 15:33 UTC, Hywan commented on crates/matrix-sdk/src/room/joined.rs
>      /// room if necessary and share a group session with them.
:+1:

2022-05-31 15:33 UTC, Hywan commented on crates/matrix-sdk/src/room/joined.rs
>      /// Does nothing if no group session needs to be shared.
:+1:

2022-05-31 17:41 UTC, poljar requested changes
Not sure if those are the same ones or if I found more :sweat_smile:.

2022-05-31 17:41 UTC, poljar commented on crates/matrix-sdk-crypto/src/machine.rs
>      /// Beware that a group session needs to be shared before this method can be
```suggestion
    /// Beware that a room key needs to be shared before this method can be
```

2022-05-31 17:41 UTC, poljar commented on crates/matrix-sdk-crypto/src/machine.rs
>      /// `room_id` - The room id of the room where the group session will be
```suggestion
    /// `room_id` - The room id of the room where the room key will be
```

2022-06-01 12:32 UTC, Hywan reviewed
Thanks for the review!

2022-06-01 12:32 UTC, Hywan commented on crates/matrix-sdk-crypto/src/machine.rs
>      /// Beware that a group session needs to be shared before this method can be
:+1:

2022-06-01 12:32 UTC, Hywan commented on crates/matrix-sdk-crypto/src/machine.rs
>      /// `room_id` - The room id of the room where the group session will be
:+1:

2022-06-01 12:32 UTC, Hywan commented on crates/matrix-sdk-crypto/src/machine.rs
>      /// `users` - The list of users that should receive the group session.
:+1:

2022-06-01 12:32 UTC, Hywan commented on crates/matrix-sdk-crypto/src/olm/group_sessions/outbound.rs
>      /// Beware that a group session needs to be shared before this method can be
:+1:

2022-06-01 12:32 UTC, Hywan commented on crates/matrix-sdk-crypto/src/session_manager/group_sessions.rs
>      /// `encryption_settings` - The settings that should be used for the group
Many others above. Fixed.

2022-06-01 13:08 UTC, poljar approved these changes
Looks good.

2022-06-01 13:08 UTC, merged