Upgrade ruma
matrix-org/matrix-rust-sdk pull request #97
Opened 2020-09-29 15:23 UTC by aledomu

2020-09-30 18:35 UTC, aledomu reviewed
Nevermind, just added another error variant.

2020-09-30 18:39 UTC, jplatte commented on matrix_sdk/src/client.rs
> +    /// # let server = Some(<&ServerName>::try_from("servername.com").unwrap());
`"servername.com".try_into().unwrap()` should work I think (looks a bit less exotic :slightly_smiling_face:)

2020-10-01 07:43 UTC, poljar requested changes
Please bump the type length limit in the WASM example over [here](https://github.com/matrix-org/matrix-rust-sdk/blob/master/matrix_sdk/examples/wasm_command_bot/src/lib.rs#L1) so the CI doesn't complain anymore:
```rust
#![type_length_limit="1702124"]
```

The rest looks good, thanks.

2020-10-01 09:24 UTC, aledomu commented
It should be good now

2020-10-01 10:23 UTC, merged